branches:
  only:
  - master
language: node_js
node_js:
- '8'
before_install:
- npm install
script:
- npm run build
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master
- provider: npm
  email: marc@marcnuri.com
  api_key: "$NPMJS_TOKEN"
env:
  global:
  - secure: UbUakOqWSRl4XlbhiimDM5YEvRtTMFL5zpB4xLSZh63kjLwLpTHLj0536ZZmoaOeBCerq1Wkjw+zlzWTyO2UMai8K9TMVWowrNxe9ORR1ptzqibLfi+JVeMy335V4jJfYWHojj5fioDg5zFmn+zp957KTfJo81klWG0CsfwjYTtHz25U+SisSlVV8FdOUz91Bia3Nrh8qhow9ZrOfZzGel8oEBvqQZNvp5cXyqRvEuAi9lKdzepLpsD1bwntpcgxj117KdSdJBxrosYZlmwRIcKtYioVbbhO3jgGu4LL/G8QfGiS7wOUk0fT4kjr/cfZg550zhd9zSUB5KXdKItD9jyc/kCUnb6oigcw4nTFJu/S0R0UoDUSIDTWXfbFbwzvwYu3NSugD7lfhk5sHxex3jAPVorpQ53hBjST6mdddxdGiaC3n9XV9RFUi+LdFWiS+R+/Ly53BxtEm3RQ/EMgbaKlHGtqYoWSDH2bE8DeA1wffWXLG5rAVaFtVzzYO/PuIouN9jUfhWA8d8QrYBPZsCMiQy1TnP/IhbEjBbxkou+FPe/bhVF/YED7LSTCEQCDrkv4+Vx7jQ+29ImPSL7IdfhTdkiuSdse28FG5gs2OpD/fjc8gKyEFiYxSAhu8XLD9A/bCKCVfHkaK40VGjQbBy944rTsPYIyCHUQiPnYrQU=
  - secure: JRFOX0e1JyUBdvvANukpU5t1WZ+/UpTh0NzwRBt03HInEkp+qLt+YEkFEHDSnmWFDVukEBu+0A98n02xWwWyMyhgcmt8S8nc8dFHVBWaKI3SLN9x8Rm+YIu/KIBhI8cvHPaHZXVy2h09ai8A/zOQPa6pG281CsVKIeGC/iHWyI57vyXLDmDEV5eS0XigAiy/W2XNI1bIReu2TA1iMjCe19CcMNIum7DE7Ghg4+cwnZuVtu40mWk7nWpPc+82YD1Lfh4IW6iKixjNxIw3LPp5HDGxPfjmgZ2gPWwwkTmTDa0Fwj5klFL14DPnCkhXxcpljTkS6KHxRihvbUsSq/Xy3+Yl8r3dfAN6gtZwvz5XqV+VtJ3UNycr03ldQwycY4Gn1dk4U6mwjs1GFluIZ7U4rgtw+ZMAX+TPVFFBGNKGcnDWnml730Xm3YV+h0Lx8PoDceKmJb1Ru82o1U9Voqi2N5kIzZJZ4qpkwfHVLXbbMQLh34GY+6SZO3fcXG8emxWzGKZlkkCWqXhRe0ggd3CWMd1xCIS6PKyn6RHu0p8dYaFHn6WDNRGdCr6C2Ha30HO76F7hcp0caXaSXLJPW2ClR7dOyJj5HcG80bbyJHV4w1EfIoABaLkfLaoqgSj/FecOHpe7Hw5j6GaXunPGN5olsqshacDZjJjq5s6KlJYyGjA=
